const express = require("express");
const app = express();
const path = require("path");
const mongoose = require("mongoose");
const Course = require("./models/Courses");

mongoose
  .connect("mongodb://localhost:27017/loginDemo", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log("Mongo database connected");
  })
  .catch((err) => {
    console.log("Mongo connection error");
    console.log(err);
  });

Course.insertMany([
  {
    name: "Getting Started with Python",
    platform: "Coursera",
    price: "FREE",
    university: "University of Michigan",
    level: "Beginner",
    pace: "Self Paced",
    rating: 3,
    link: "https://www.coursera.org/learn/python",
  },
  {
    name: "Machine Learning Engineer for Microsoft",
    platform: "Udacity",
    price: "PAID",
    university: "Microsoft",
    level: "Intermediate",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udacity.com/course/machine-learning-engineer-for-microsoft-azure-nanodegree--nd00333",
  },
  {
    name: "Getting Started with AI using IBM Watson",
    platform: "Udacity",
    price: "PAID",
    university: "IBM",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.coursera.org/learn/ai-with-ibm-watson?specialization=applied-artifical-intelligence-ibm-watson-ai",
  },
  {
    name: "The Complete JavaScript Course 2022: From Zero to Expert!",
    platform: "Udemy",
    price: "PAID",
    university: "Jonas Schmedtmann",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/the-complete-javascript-course/",
  },
  {
    name: "Introduction to R",
    platform: "Datacamp",
    price: "FREE",
    university: "Datacamp",
    level: "Beginner",
    pace: "4 hours",
    rating: 4,
    link: "https://www.datacamp.com/courses/free-introduction-to-r",
  },
  {
    name: "Introduction to Power BI",
    platform: "Datacamp",
    price: "FREE",
    university: "Datacamp",
    level: "Beginner",
    pace: "6 hours",
    rating: 4,
    link: "https://www.datacamp.com/courses/introduction-to-power-bi",
  },
  {
    name: "A/B Testing",
    platform: "Udacity",
    price: "FREE",
    university: "Google",
    level: "Intermediate",
    pace: "Self Paced",
    rating: 3,
    link: "https://www.udacity.com/course/ab-testing--ud257",
  },
  {
    name: "Google IT Automation with Python",
    platform: "Coursera",
    price: "PAID",
    university: "Google",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.coursera.org/professional-certificates/google-it-automation",
  },
  {
    name: "Ultimate AWS Certified Solutions Architect Associate 2021",
    platform: "Udemy",
    price: "PAID",
    university: "Stephane Maarek",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c02/",
  },
  {
    name: "Introduction to TensorFlow Lite",
    platform: "Udacity",
    price: "FREE",
    university: "Tensorflow Lite",
    level: "Intermediate",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udacity.com/course/intro-to-tensorflow-lite--ud190",
  },
  {
    name: "IBM AI Foundations for Business",
    platform: "Coursera",
    price: "PAID",
    university: "IBM",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.coursera.org/specializations/ibm-ai-foundations-for-business",
  },
  {
    name: "Microsoft Excel - Excel from Beginner to Advanced",
    platform: "Udemy",
    price: "PAID",
    university: "Kyle Pew, Office Newb",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/microsoft-excel-2013-from-beginner-to-advanced-and-beyond/",
  },
  {
    name: "Introduction to Data Science",
    platform: "Coursera",
    price: "PAID",
    university: "IBM",
    level: "Beginner",
    pace: "Self Paced",
    rating: 3,
    link: "https://www.coursera.org/specializations/introduction-data-science",
  },
  {
    name: "Knowledge-Based AI: Cognitive Systems",
    platform: "Udacity",
    price: "FREE",
    university: "Georgia Tech",
    level: "Advanced",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udacity.com/course/knowledge-based-ai-cognitive-systems--ud409",
  },
  {
    name: "The Data Science Course 2021: Complete Data Science Bootcamp",
    platform: "Udemy",
    price: "PAID",
    university: "365 Careers",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/the-data-science-course-complete-data-science-bootcamp/",
  },
  {
    name: "Object-Oriented Programming in Python",
    platform: "Datacamp",
    price: "FREE",
    university: "Datacamp",
    level: "Intermediate",
    pace: "4 hours",
    rating: 4,
    link: "https://www.datacamp.com/courses/object-oriented-programming-in-python",
  },
  {
    name: "DevOps on AWS",
    platform: "Coursera",
    price: "PAID",
    university: "AWS",
    level: "Intermediate",
    pace: "Self Paced",
    rating: 5,
    link: "https://www.coursera.org/specializations/aws-devops",
  },
  {
    name: "Machine Learning DevOps Engineer",
    platform: "Udacity",
    price: "PAID",
    university: "Udacity",
    level: "Advanced",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udacity.com/course/machine-learning-dev-ops-engineer-nanodegree--nd0821",
  },
  {
    name: "The Complete SQL Bootcamp 2022: Go from Zero to Hero",
    platform: "Udemy",
    price: "PAID",
    university: "Jose Portilla",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/the-complete-sql-bootcamp/",
  },
  {
    name: "Machine Learning",
    platform: "Coursera",
    price: "PAID",
    university: "Stanford University",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.coursera.org/learn/machine-learning",
  },
  {
    name: "Self-Driving Fundamentals: Featuring Apollo",
    platform: "Udacity",
    price: "FREE",
    university: "Udacity x Baidu Apollo",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udacity.com/course/self-driving-car-fundamentals-featuring-apollo--ud0419",
  },
  {
    name: "The Complete Digital Marketing Course - 12 Courses in 1",
    platform: "Udemy",
    price: "PAID",
    university: "Rob Percival, Daragh Walsh",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/learn-digital-marketing-course/",
  },
  {
    name: "Managing Remote Teams with Upwork",
    platform: "Udacity",
    price: "FREE",
    university: "Upwork",
    level: "Beginner",
    pace: "Self Paced",
    rating: 3,
    link: "https://www.udacity.com/course/managing-remote-teams-with-upwork--ud942",
  },
  {
    name: "Data Science Fundamentals with Python and SQL",
    platform: "Coursera",
    price: "PAID",
    university: "IBM",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.coursera.org/specializations/data-science-fundamentals-python-sql",
  },
  {
    name: "Flutter & Dart - The Complete Guide [2022 Edition]",
    platform: "Udemy",
    price: "PAID",
    university: "Academind by Maximilian Schwarzmüller",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/",
  },
  {
    name: "AWS Cloud Practitioner Essentials",
    platform: "Coursera",
    price: "PAID",
    university: "AWS",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.coursera.org/learn/aws-cloud-practitioner-essentials",
  },
  {
    name: "Google UX Design",
    platform: "Coursera",
    price: "PAID",
    university: "Google",
    level: "Beginner",
    pace: "Self Paced",
    rating: 5,
    link: "https://www.coursera.org/professional-certificates/google-ux-design",
  },
  {
    name: "Android Basics: Multiscreen Apps",
    platform: "Udacity",
    price: "FREE",
    university: "Google",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udacity.com/course/android-basics-multiscreen-apps--ud839",
  },
  {
    name: "IBM Data Science",
    platform: "Coursera",
    price: "PAID",
    university: "IBM",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.coursera.org/professional-certificates/ibm-data-science",
  },
  {
    name: "Introduction to SQL",
    platform: "Datacamp",
    price: "FREE",
    university: "Datacamp",
    level: "Beginner",
    pace: "4 hours",
    rating: 4,
    link: "https://www.datacamp.com/courses/introduction-to-sql",
  },
  {
    name: "AWS Fundamentals",
    platform: "Coursera",
    price: "PAID",
    university: "AWS",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.coursera.org/specializations/aws-fundamentals",
  },
  {
    name: "Learn Ethical Hacking From Scratch",
    platform: "Udemy",
    price: "PAID",
    university: "Zaid Sabih, z Security",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/learn-ethical-hacking-from-scratch/",
  },
  {
    name: "Introduction to Python",
    platform: "Datacamp",
    price: "FREE",
    university: "Datacamp",
    level: "Beginner",
    pace: "4 hours",
    rating: 4,
    link: "https://www.datacamp.com/courses/intro-to-python-for-data-science",
  },
  {
    name: "UX Design for Mobile Developers",
    platform: "Udacity",
    price: "FREE",
    university: "Google",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udacity.com/course/ux-design-for-mobile-developers--ud849",
  },
  {
    name: "The Ultimate MySQL Bootcamp: Go from SQL Beginner to Expert",
    platform: "Udemy",
    price: "PAID",
    university: "Colt Steele, Ian Schoonover",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/the-ultimate-mysql-bootcamp-go-from-sql-beginner-to-expert/",
  },
  {
    name: "Introduction to Virtual Reality",
    platform: "Udacity",
    price: "FREE",
    university: "Google VR",
    level: "Beginner",
    pace: "Self Paced",
    rating: 3,
    link: "https://www.udacity.com/course/localization-essentials--ud610",
  },
  {
    name: "Google Data Analytics",
    platform: "Coursera",
    price: "PAID",
    university: "Google",
    level: "Beginner",
    pace: "Self Paced",
    rating: 5,
    link: "https://www.coursera.org/professional-certificates/google-data-analytics",
  },
  {
    name: "The Complete Cryptocurrency Course: More than 5 Courses in 1",
    platform: "Udemy",
    price: "PAID",
    university: "Chris Haroun",
    level: "Beginner",
    pace: "Self Paced",
    rating: 4,
    link: "https://www.udemy.com/course/the-complete-cryptocurrency-course-more-than-5-courses-in-1/",
  },
]).then((data) => {
  console.log("worked");
});
